# Generated by Django 2.0.3 on 2019-07-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='price',
            new_name='small_price',
        ),
        migrations.AddField(
            model_name='items',
            name='large_price',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
