# Generated by Django 2.0.3 on 2019-07-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190729_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='large_price',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='small_price',
            field=models.CharField(max_length=16),
        ),
    ]
