# Generated by Django 2.0.3 on 2019-07-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190729_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='number_toppings',
            field=models.CharField(blank=True, default='none', max_length=2),
        ),
    ]
