# Generated by Django 2.0.3 on 2019-08-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20190814_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='number_toppings',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
