# Generated by Django 2.0.3 on 2019-08-14 12:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20190814_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 14, 12, 56, 45, 615796, tzinfo=utc)),
        ),
    ]
