# Generated by Django 2.0.3 on 2019-07-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_items_number_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='number_toppings',
            field=models.IntegerField(blank=True, default='none'),
        ),
    ]
