# Generated by Django 2.0.3 on 2019-08-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190809_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppings',
            name='topp',
        ),
        migrations.DeleteModel(
            name='Toppings',
        ),
    ]
