# Generated by Django 2.0.3 on 2019-08-14 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190814_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='client',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='topping',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='topping_steak',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
