# Generated by Django 2.0.3 on 2019-08-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_items_number_toppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='number_toppings',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
