# Generated by Django 2.0.3 on 2019-08-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20190814_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='number_toppings',
            field=models.CharField(blank=True, default='none', max_length=4),
        ),
    ]
