# Generated by Django 2.0.3 on 2019-08-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20190814_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='topping',
            field=models.CharField(blank=True, default='none', max_length=64),
        ),
        migrations.AlterField(
            model_name='orders',
            name='topping_steak',
            field=models.CharField(blank=True, default='none', max_length=64),
        ),
    ]
