# Generated by Django 2.0.3 on 2019-08-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_orders_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
